---
defaults: &defaults
  docker:
    - image: gcr.io/planet-4-151612/circleci-base:latest
  working_directory: /home/circleci/app

version: 2

jobs:
  build-dev:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: activate-gcloud-account.sh
      - run: make checkout-master
      - run: make build
      - run: make dev-push
      - run: make dev

  build-prod:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: activate-gcloud-account.sh
      - run: make checkout-tag
      - run: make build
      - run: make prod-push
      - run: make prod

workflows:
  version: 2
  prod:
    jobs:
      - build-prod:
          context: org-global
          filters:
            branches:
              only: master
  dev:
    jobs:
      - build-dev:
          context: org-global
          filters:
            branches:
              only: develop
